// @flow
import fs from 'fs';
import path from 'path';
import SVGO from 'svgo';
import glob from 'glob';
import util from 'util';
import yargs from 'yargs';
import prettier from 'prettier';

const globAsync = util.promisify(glob);
const readFileAsync = util.promisify(fs.readFile);
const writeFileAsync = util.promisify(fs.writeFile);

const svgo = new SVGO({
  floatPrecision: 4,
  plugins: [
    { cleanupAttrs: true },
    { removeDoctype: true },
    { removeXMLProcInst: true },
    { removeComments: true },
    { removeMetadata: true },
    { removeTitle: true },
    { removeDesc: true },
    { removeUselessDefs: true },
    { removeXMLNS: true },
    { removeEditorsNSData: true },
    { removeEmptyAttrs: true },
    { removeHiddenElems: true },
    { removeEmptyText: true },
    { removeEmptyContainers: true },
    { removeViewBox: true },
    { cleanupEnableBackground: true },
    { minifyStyles: true },
    { convertStyleToAttrs: true },
    { convertColors: true },
    { convertPathData: true },
    { convertTransform: false },
    { removeUnknownsAndDefaults: true },
    { removeNonInheritableGroupAttrs: true },
    { removeUselessStrokeAndFill: true },
    { removeUnusedNS: true },
    { cleanupIDs: true },
    { cleanupNumericValues: true },
    { cleanupListOfValues: true },
    { moveElemsAttrsToGroup: true },
    { moveGroupAttrsToElems: true },
    { collapseGroups: true },
    { removeRasterImages: true },
    { mergePaths: true },
    { convertShapeToPath: true },
    { sortAttrs: true },
    { removeDimensions: true },
    { removeAttrs: true },
    { removeElementsByAttr: true },
    { removeStyleElement: true },
    { removeScriptElement: true },
  ],
});

const getIconNameFromPath = (icon: string): string =>
  icon
    .split('/')
    .pop()
    .toLowerCase()
    .replace(' ', '_')
    .replace('.svg', '');

const getOptimizedIcon = async (icon: string): Promise<string> => {
  const input = icon
    .replace(/ fill="#ADB5BD"/g, '')
    .replace(/ fill="none"/g, '')
    .replace(/<rect(.*)rect>/g, '<rect fill="none" x="0" y="0" width="24" height="24"></rect>');

  const result = await svgo.optimize(input);

  return result.data
    .replace(/<svg[^>]*>/g, '')
    .replace(/<\/svg>/g, '')
    .replace(/"\/>/g, '" />')
    .replace(/fill-opacity=/g, 'fillOpacity=')
    .replace(/xlink:href=/g, 'xlinkHref=')
    .replace(/clip-rule=/g, 'clipRule=')
    .replace(/fill-rule=/g, 'fillRule=')
    .replace(/stroke-width=/g, 'strokeWidth=')
    .replace(/ clip-path=".+?"/g, '')
    .replace(/<clipPath.+?<\/clipPath>/g, '');
};

const generateJSOutput = (icons: { [key: string]: string }): string => `
  // Warning: do not edit this file manually, it is generated by a script
  // To add add or update an icon, place it in the src/icons directory and run yarn build:icons

  import React from 'react';

  export default {
    ${Object.keys(icons)
      .map(key => `${key}: (${icons[key]}),\n`)
      .join('')}
  }
`;

type ArgvType = {
  iconDir: string,
  outputFile: string,
  glob?: string,
};

const init = async ({ iconDir, outputFile, glob = '*.svg' }: ArgvType) => {
  try {
    const iconPaths = await globAsync(path.join(iconDir, glob));
    const icons = {};

    console.log(`Found ${iconPaths.length} icons`);

    for (const iconPath of iconPaths) {
      const data = await readFileAsync(iconPath, { encoding: 'utf8' });
      const iconName = getIconNameFromPath(iconPath);

      console.log(`Optimizing ${iconName} icon...`);

      const optimizedIcon = await getOptimizedIcon(data);

      icons[iconName] = optimizedIcon;
    }

    const outputJS = generateJSOutput(icons);
    const prettierConfig = await prettier.resolveConfig(process.cwd());
    const formattedOutputJS = prettier.format(
      outputJS,
      Object.assign(prettierConfig, { parser: 'babylon' })
    );

    await writeFileAsync(outputFile, formattedOutputJS);

    console.log('Success!');

    process.exit(0);
  } catch (e) {
    console.error(e);
    process.exit(1);
  }
};

if (require.main === module) {
  const argv = yargs
    .usage('Extract SVG paths for React Icon component.\nUsage: $0 [args]')
    .demandOption('output-file')
    .describe('output-file', 'Location of output file')
    .demandOption('icon-dir')
    .describe('icon-dir', 'Icon directory')
    .describe('glob', 'Glob to match inside of --svg-dir. Default *.svg').argv;

  init(argv);
}

export default init;
