export default {
  Primary: 'primary',
  Secondary: 'secondary',
  'Tertiary Red': 'tertiary-red',
  'Tertiary green': 'tertiary-green',
  'Tertiary black': 'tertiary-black',
  Academy: 'academy',
  Success: 'success',
  Info: 'info',
  Warning: 'warning',
  Danger: 'danger',
  Light: 'light',
  Dark: 'dark',
  'Gray 100': 'gray-100',
  'Gray 200': 'gray-200',
  'Gray 300': 'gray-300',
  'Gray 400': 'gray-400',
  'Gray 500': 'gray-500',
  'Gray 600': 'gray-600',
  'Gray 700': 'gray-700',
  'Gray 800': 'gray-800',
  'Gray 900': 'gray-900',
  Facebook: 'facebook',
  Twitter: 'twitter',
  LinkedIn: 'linkedin',
  Instagram: 'instagram',
} as const;
